### ISSUE TITLE
Error: Cannot find module

### ISSUE THREAD

**Issue by chandanpg** [github/local-action#148]
Hi, I am getting error below. Note that my current repository is at path like "C:\Users\username\OneDrive - Org\Documents\Projects\". I think this issue is  coming because of space in path name. I tried in WSL and Windows but both places i am getting same error.  Can you check on this ? 

Also i am wondering if if i am running from WSL, why it would still same path windows.

Error: Cannot find module 'C:\\Users\\username\\OneDrive'
Require stack:
- internal/preload
    at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
    at Module._load (node:internal/modules/cjs/loader:986:27)
    at internalRequire (node:internal/modules/cjs/loader:176:19)
    at Module._preloadModules (node:internal/modules/cjs/loader:1563:5)
    at loadPreloadModules (node:internal/process/pre_execution:730:5)
    at setupUserModules (node:internal/process/pre_execution:206:5)
    at prepareExecution (node:internal/process/pre_execution:159:5)
    at prepareMainThreadExecution (node:internal/process/pre_execution:54:10)
    at node:internal/main/run_main_module:11:19 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'internal/preload' ]
}

**Comment by chandanpg** [comment]
> Heyo! 👋
> 
> Can you tell me the full command you are using to run `local-action`?

npx local-action . src/main.ts .env

**Comment by ncalteen** [comment]
I was able to reproduce the issue on my Windows machine and find the error. It looks like the problem was the bootstrap script that runs before the main `local-action` code. I didn't have the value properly quoted :(

I just published v2.6.2. This one should take care of the issue. If you see any problems please add a comment here and I will reopen and investigate.

**Comment by chandanpg** [comment]
Looks like its still throwing me error but this time its different error. 

 npx local-action . src/main.ts .env
     _        _   _               ____       _
    / \   ___| |_(_) ___  _ __   |  _ \  ___| |__  _   _  __ _  __ _  ___ _ __
   / _ \ / __| __| |/ _ \| '_ \  | | | |/ _ \ '_ \| | | |/ _` |/ _` |/ _ \ '__|
  / ___ \ (__| |_| | (_) | | | | | |_| |  __/ |_) | |_| | (_| | (_| |  __/ |
 /_/   \_\___|\__|_|\___/|_| |_| |____/ \___|_.__/ \__,_|\__, |\__, |\___|_|
                                                         |___/ |___/
================================================================================
                                 Configuration
================================================================================

┌─────────┬────────────────────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ (index) │ Field              │ Value
                                    │
├─────────┼────────────────────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ 0       │ 'Action Path'      │ 'C:\\Users\\my-name\\OneDrive - MyComp\\Documents\\my-repo'               │
│ 1       │ 'Entrypoint'       │ 'C:\\Users\\my-name\\OneDrive - MyComp\\Documents\\my-repo\\src\\main.ts' │
│ 2       │ 'Environment File' │ 'C:\\Users\\my-name\\OneDrive - MyComp\\Documents\\my-repo\\.env'         │
└─────────┴────────────────────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

================================================================================
                                Action Metadata
================================================================================

┌─────────┬─────────────────────────┬─────────────────────────────────────────────────────────────────┐
│ (index) │ Input                   │ Description                                                     │
├─────────┼─────────────────────────┼─────────────────────────────────────────────────────────────────┤
│ 0       │ 'REPO_NAME'             │ 'Repository Name'                                               │
│ 1       │ 'DEVOPS_PAT'            │ 'DevOps Personal Access Token'                                  │
│ 2       │ 'FRAMEWORK'             │ 'Framework of repository'                                       │
│ 3       │ 'IMAGE_NAME'            │ 'Image'                                                         │                                  │
└─────────┴─────────────────────────┴─────────────────────────────────────────────────────────────────┘

┌─────────┐
│ (index) │
├─────────┤
└─────────┘

================================================================================
                                 Running Action
================================================================================

node:internal/process/promises:391
    triggerUncaughtException(err, true /* fromPromise */);
    ^
Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'C:\Users\my-name\OneDrive - MyComp\Documents\my-repo\node_modules\@actions\github\lib\github.js' imported from C:\Users\my-name\AppData\Roaming\npm\node_modules\@github\local-action\node_modules\quibble\lib\esm-import-functions.js
    at finalizeResolution (node:internal/modules/esm/resolve:265:11)
    at moduleResolve (node:internal/modules/esm/resolve:933:10)
    at defaultResolve (node:internal/modules/esm/resolve:1169:11)
    at nextResolve (node:internal/modules/esm/hooks:866:28)
    at resolveBase (file:///C:/Users/my-name/AppData/Local/npm-cache/_npx/fd45a72a545557e9/node_modules/tsx/dist/esm/index.mjs?1739870646490:2:3212)
    at resolveDirectory (file:///C:/Users/my-name/AppData/Local/npm-cache/_npx/fd45a72a545557e9/node_modules/tsx/dist/esm/index.mjs?1739870646490:2:3584)
    at resolveTsPaths (file:///C:/Users/my-name/AppData/Local/npm-cache/_npx/fd45a72a545557e9/node_modules/tsx/dist/esm/index.mjs?1739870646490:2:4073)
    at resolve (file:///C:/Users/my-name/AppData/Local/npm-cache/_npx/fd45a72a545557e9/node_modules/tsx/dist/esm/index.mjs?1739870646490:2:4447)
    at nextResolve (node:internal/modules/esm/hooks:866:28)
    at resolve (file:///C:/Users/my-name/AppData/Roaming/npm/node_modules/@github/local-action/node_modules/quibble/lib/quibble.mjs:25:5) {
  code: 'ERR_MODULE_NOT_FOUND',
  url: 'file:///C:/Users/my-name/OneDrive%20-%20MyComp/Documents/my-repo/node_modules/@actions/github/lib/github.js'
}

Node.js v20.15.1

**Comment by ncalteen** [comment]
Can you share your `package.json`? Also, have you installed all dependencies with `npm install`?

**Comment by chandanpg** [comment]
Hi Please ignore. Looks like its working now. I must have been doing something wrong earlier.
