### ISSUE TITLE
Cannot find module error

### ISSUE THREAD

**Issue by watercable76** [github/local-action#168]
I recently upgraded the local-action to 2.6.4 and keep getting this error when attempting to run:

`Error: Cannot find module 'C:\C:\Users\n.cable\Documents\GIT\cleanup-action\src\main.ts'`  

I created this project over a year ago and have kept up with other dependencies, but this is making it so I can't test locally and verify my changes are working

Current version: 2.2.0
Last working version: 2.6.0
Attempted upgraded version: 2.6.1+

**Comment by ncalteen** [comment]
Can you try the latest version of `@github/local-action`? v3.1.1

**Comment by watercable76** [comment]
I updated, same issue that @fknittel was having. Only difference is I'm using Node.js v22.6.0

Here is the command to run the action: `npx local-action ./ src/main.ts .env`
This is what I've been using since I updated to use the typescript template, so at least 6-8 months by this point

**Comment by ncalteen** [comment]
I believe I found the issue. It looks like the utility is trying to stub all of the supported `@actions/toolkit` libraries. If one is not installed in the project, the stub will fail. I've published version 3.1.2 that should include the fix. Please install that and try it out!

**Comment by fknittel** [comment]
@ncalteen Thanks for the update. Unfortunately, it doesn't appear to fix the issue: https://github.com/fknittel/reproduce-local-action-issue-168/actions/runs/14124434871/job/39570394901

**Comment by ncalteen** [comment]
Ah I think I found it this time! Since the reproduction you linked is a CommonJS action, `local-action` requires a slightly different entrypoint setting. Please install and try version 3.1.3. If that seems to have resolved the issue, I will work on setting up additional CI tests on Windows runners to catch these problems in the future.

**Comment by watercable76** [comment]
Just updated to 3.1.3, action is running locally again. Thanks for finding the fix!
